language: csharp

sudo: required
dist: xenial

os:
  - linux

env:
  matrix:
    - CLI_VERSION=1.0.0-preview2-003121

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003121
  
script:
  - dotnet restore --infer-runtimes
  - dotnet test ./src/Tests