sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - CLI_VERSION=1.0.0-preview2-003121
    - CLI_ARCH=x64
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update

install:
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003121
  - dotnet --info
  
script:
  - dotnet restore --infer-runtimes
  - dotnet test ./src/Tests